name: 'api_explorer'
version: 0.0.1
description: >
  A webapplication written in polymer.dart, that allows to explore api's which publish a google api discovery document.
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: '>=0.15.4 <0.16.0'
  paper_elements: '>=0.6.1 <0.7.0'
  route_hierarchical: any
  http: any
  google_oauth2_client: '>=0.3.2 <0.4.0'
transformers:
- polymer:
    entry_points: web/index.html
